[project]
name = "fake-users-api"
version = "0.1.0"
description = "Generate fake users"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.4.0",
    "fastapi[standard]>=0.115.14",
]
